@startuml
title 远程调试架构

package intellij {
   [代码断点]
}

package jetty服务器 {
   [resteasy服务]
}

note left of jetty服务器
基于debug模式运行
end note

代码断点 -down-> resteasy服务 : 对应

User -down-> intellij : 使用
@enduml